### ISSUE TITLE
Image files are larger than necessary

### ISSUE THREAD

**Issue by stblassitude** [stblassitude/packer-freebsd#1]
It appears the image files do not shrink properly in the cleanup.sh and zerodisk.sh scripts. Although the complete box needs about 400 to 500 MB, the image file is up to 750 MB large.

This might be due to VirtualBox not supporting TRIM properly; it seems this has to be told to VirtualBox when creating the initial image.

**Comment by stefanbethke** [comment]
TRIM support seems to be flaky; reactivating scripts/zerodisk.sh however gives good results.

**Comment by stblassitude** [comment]
TRIM support seems to be flaky; reactivating scripts/zerodisk.sh however gives good results.
